language: objective-c
podfile: Example/Podfile
before_install:
  # https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-257964767
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone SE (10" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
before_script:
  - rvm get head || true # https://github.com/travis-ci/travis-ci/issues/6307
script: 
  - travis_retry scan --device 'iPhone SE'
after_success:
  - bundle exec slather
  - bash <(curl -s https://codecov.io/bash)
